/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#777575",
        "on-secondary-fixed-variant": "#00586c",
        "primary-dim": "#00ec93",
        "on-error": "#490006",
        "on-primary-fixed-variant": "#00653c",
        "surface-bright": "#2c2c2c",
        "on-tertiary-fixed-variant": "#6c6d6e",
        "secondary-fixed": "#79dfff",
        "on-error-container": "#ffa8a3",
        "tertiary-fixed": "#ffffff",
        "surface-container-highest": "#262626",
        "surface-tint": "#a0ffc4",
        "primary": "#a0ffc4",
        "tertiary-fixed-dim": "#f0f1f1",
        "error-dim": "#d7383b",
        "error": "#ff716c",
        "surface-variant": "#262626",
        "on-secondary-container": "#eefaff",
        "on-surface-variant": "#adaaaa",
        "secondary-container": "#00677e",
        "surface-container": "#1a1919",
        "secondary-fixed-dim": "#1cd5ff",
        "on-secondary-fixed": "#003a47",
        "secondary-dim": "#00c3eb",
        "primary-fixed": "#00fc9d",
        "inverse-on-surface": "#565554",
        "on-tertiary-fixed": "#4f5051",
        "inverse-surface": "#fcf8f8",
        "on-tertiary-container": "#555757",
        "on-tertiary": "#5e5f60",
        "surface": "#0e0e0e",
        "surface-dim": "#0e0e0e",
        "on-primary": "#00643b",
        "primary-container": "#00fc9d",
        "outline-variant": "#494847",
        "primary-fixed-dim": "#00ec93",
        "on-secondary": "#004352",
        "tertiary": "#f9f9f9",
        "surface-container-lowest": "#000000",
        "tertiary-dim": "#ebebeb",
        "on-primary-fixed": "#004528",
        "inverse-primary": "#006d41",
        "surface-container-high": "#201f1f",
        "secondary": "#00d2fd",
        "on-background": "#ffffff",
        "error-container": "#9f0519",
        "on-surface": "#ffffff",
        "surface-container-low": "#131313",
        "on-primary-container": "#005b35",
        "tertiary-container": "#ebebeb",
        "background": "#0e0e0e"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
        "editorial": ["Syne", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
